# Generated by Django 5.0.1 on 2024-07-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ez_care", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="command",
        ),
    ]
